version: '2'

services:

  piface-relay:

    build: .

    devices:
      # the spi bus
      - "/dev/ttyAMA0:/dev/ttyAMA0"
    volumes:
      - "./:/srv"
    command: python /srv/pfr_test.py
    privileged: true

